### ISSUE TITLE
Automatically copy `.env` files

### ISSUE THREAD

**Issue by YuKitsune** [YuKitsune/Configuration.Env#5]
It'd be great if projects consuming the NuGet Package could have their `.env` files automatically copied to the output directory on build. This is the current behaviour for ASP.NET Core projects and `.json` files.

**Comment by DevD4v3** [comment]
Any news on this feature?

**Comment by YuKitsune** [comment]
@MrDave1999 This should now be available in [v1.0.4](https://www.nuget.org/packages/YuKitsune.Configuration.Env/1.0.4)
